ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from home import views
from order import views as OrderViews
from user import views as UserViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('user/', include('user.urls'), name="user"),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('about/', views.aboutus, name='aboutus'),
    path('contact/', views.contact, name='contact'),

    path('search/', views.search, name='search'),
    path('search_auto/', views.search_auto, name='search_auto'),
    path('ajaxcolor/', views.ajaxcolor, name='ajaxcolor'),
    path('faq/', views.faq, name='faq'),

    path('category/<int:id>/<slug:slug>',
         views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>',
         views.product_detail, name='product_detail'),

    path('shopcart/', OrderViews.shopcart, name='shopcart'),

    path('shopcart/', OrderViews.shopcart, name='shopcart'),

    path('login/', UserViews.login_form, name='login_form'),
    path('signup/', UserViews.signup_form, name='signup_form'),
    path('logout/', UserViews.logout_func, name='logout_func'),
    path('profile/', UserViews.profile, name='profile'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path, include

from . import views


urlpatterns = [
    path('', views.index, name='index')
]

order/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('addtoshopcart/<int:id>', views.addtoshopcart, name='addtoshopcart'),
    path('deletefromcart/<int:id>',
         views.deletefromcart, name='deletefromcart'),
    path('orderproduct/',
         views.orderproduct, name='orderproduct'),

]

order/models.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.db import models


# Create your models here.
from product.models import Product, Variants


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    variant = models.ForeignKey(
        Variants, on_delete=models.SET_NULL, blank=True, null=True)  # relation with varinat
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)

    @property
    def varamount(self):
        return (self.quantity * self.variant.price)


class ShopCartForm(ModelForm):

    class Meta:
        model = ShopCart
        fields = ['quantity']


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=100)
    total = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=10, default='New')
    ip = models.CharField(blank=True, max_length=20)
    adminnote = models.CharField(blank=True, max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'address', 'phone', 'city']


class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )

    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ForeignKey(
        Variants, on_delete=models.SET_NULL, blank=True, null=True)  # relation with varinat
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()

    status = models.CharField(choices=STATUS, max_length=10, default='New')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/views.py
from django.shortcuts import HttpResponse, HttpResponseRedirect, render
from django.contrib.auth.decorators import login_required
from django.utils.crypto import get_random_string
from django.contrib import messages

from .models import ShopCart, ShopCartForm, OrderForm, OrderProduct, Order
from product.models import Category, Product
from user.models import UserProfile
# Create your views here.


def index(request):
    return HttpResponse('teste')


@login_required(login_url='/login')
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')
    current_user = request.user

    checkproduct = ShopCart.objects.filter(product_id=id)

    if checkproduct:
        control = 1
    else:
        control = 0

    print('teste')
    if request.method == 'POST':
        print('teste')
        print('teste2')
        form = ShopCartForm(request.POST)
        print(form)
        if form.is_valid():
            if control == 1:
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()
            else:
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, 'Product added to shopcart')
        return HttpResponseRedirect(url)
    else:
        print('2')
        if control == 1:
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else:
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()  #
        messages.success(request, "Product added to Shopcart")
        return HttpResponseRedirect(url)


def shopcart(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for product in shopcart:
        total += product.product.price * product.quantity

    context = {
        'category': category, 'shopcart': shopcart, 'total': total}

    return render(request, 'shopcart_products.html', context)


@login_required(login_url='/login')
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Seu item foi deletado')
    return HttpResponseRedirect('/shopcart')


@login_required(login_url='/login')
def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.filter(user_id=current_user.id)
    total = 0
    for item in shopcart:
        total += item.product.price * item.quantity

    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get('REMOTE_ADDR')
            ordercode = get_random_string(5).upper()
            data.code = ordercode
            data.save()

            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id
                detail.product_id = rs.product_id
                detail.user_id = current_user.id
                detail.quantity = rs.quantity
                detail.price = rs.price
                detail.amount = rs.amount
                detail.save()

                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()

            ShopCart.objects.filter(user_id=current_user.id).delete()
            request.session['cart_items'] = 0
            messages.success(
                request, 'Your order has been completed, Thank You')
            return render(request, 'order_completed.html', {'ordercode': ordercode, 'category': category})
        else:
            messages.warning(request, form.errors)
            return HttpResponse('/order/orderproduct')

    form = OrderForm()
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'shopcart': shopcart,
               'category': category,
               'total': total,
               'form': form,
               'profile': profile}

    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{% extends 'homebase.html' %}

{% block title %} Order Complated {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="/">Home</a></li>
            <li class="active">Order Complated</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->
<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Order Complated</h3>
                    </div>
                    <hr>
                    <h2>Dear {{ user.first_name }} {{  user.last_name }}</h2>
                    <hr>
                    <h3>Your order is completed</h3>
                    <h3>Order Code : {{ ordercode }}</h3>
                    <h3>Thank You</h3>
                    <hr>

                </div>

            </div>


        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->

{% endblock %}

order/templates/order_form.html
{% extends 'homebase.html' %}

{% block title %} Shopcart {% endblock  %}
{% block description %} Comprar {% endblock  %}
{% block keywords %} compra {% endblock  %}

{% block sidebar  %} {% include 'sidebar.html' %} {% endblock  %}
{% comment %} {% block slider  %} {% include 'slider.html' %} {% endblock  %} {% endcomment %}

{% block body  %}

<div class="container">
    <!-- row -->
    <div class="row">
        <Form action="" method="post">
            {% csrf_token %}
            <div class="col-md-6">
                <div class="billing-details">

                    <div class="section-title">
                        <h4 class="title">Shipping Details</h4>
                    </div>
                    <p><label for="id_first_name">First name:</label>
                        <input type="text" name="first_name" value="{{ user.first_name }}" class="input" maxlength="10"
                            required id="id_first_name"></p>
                    <p><label for="id_last_name">Last name:</label>
                        <input type="text" name="last_name" value="{{ user.last_name }}" class="input" maxlength="10"
                            required id="id_last_name"></p>
                    <p><label for="id_address">Address:</label>
                        <input type="text" name="address" value="{{ profile.address }}" class="input" maxlength="150"
                            id="id_address"></p>
                    <p><label for="id_phone">Phone:</label>
                        <input type="text" name="phone" value="{{ profile.phone }}" class="input" maxlength="20"
                            id="id_phone"></p>
                    <p><label for="id_city">City:</label>
                        <select name="city" class="input" id="id_city">
                            <option value="{{ profile.city }}" selected>{{ profile.city }}</option>
                            <option value="İstanbul">Istanbul</option>
                            <option value="Ankara">Ankara</option>
                            <option value="İzmir">Izmir</option>
                            <option value="Bursa">Bursa</option>
                            <option value="Konya">Konya</option>
                            <option value="Yozgat">Yozgat</option>
                        </select></p>
                    <p><label for="id_first_name">Country :</label>
                        <input type="text" name="country" class="input" id="id_country" value="{{ profile.country }}">
                    </p>
                    <div class="pull-right">
                        <button type="submit" class="primary-btn">Complete Order</button>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="shiping-methods">
                    <div class="section-title">
                        <h4 class="title">Payment Information</h4>
                    </div>
                    <p><label for="id_first_name">Total: {{ total }} USD </label>
                        <input type="text" name="total" class="input" readonly
                            value="{% comment %} ${{ total|currency:request.session.currency }} {{ request.session.currency }} {% endcomment %}">
                    </p>
                    <p><label for="id_first_name">Credit Card Holder</label>
                        <input type="text" name="holder" class="input" value=""></p>
                    <p><label for="id_first_name">Credit Card Number</label>
                        <input type="text" name="number" class="input" value=""></p>
                    <p><label for="id_first_name">Credit Exp Date/Year</label>
                        <input type="text" name="ecpdate" class="input" placeholder="mm/yy"></p>
                    <p><label for="id_first_name">Security Number</label>
                        <input type="text" name="secnumber" class="input" value=""></p>
                </div>
            </div>

        </Form>
    </div>
</div>

{% endblock  %}


{% block footer  %} {% include 'footer.html' %} {% endblock  %}

order/templates/shopcart_products.html
{% extends 'homebase.html' %}

{% block title %} Shopcart {% endblock  %}
{% block description %} {{ setting.description }} {% endblock  %}
{% block keywords %} {{ setting.keywords }} {% endblock  %}

{% block sidebar  %} {% include 'sidebar.html' %} {% endblock  %}
{% comment %} {% block slider  %} {% include 'slider.html' %} {% endblock  %} {% endcomment %}

{% block body  %}

<!-- Wishlist Start -->
<div class="wishlist-page">
    <div class="container-fluid">
        <div class="wishlist-page-inner">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Produto</th>
                                    <th>Preço</th>
                                    <th>Quantidade</th>
                                    <th>Total</th>
                                    <th>Remover</th>

                                </tr>
                            </thead>
                            <tbody class="align-middle">
                                {% for shop in shopcart %}
                                <tr>
                                    <td>
                                        <div class="img">
                                            <a href="#"><img src="{{shop.product.image.url}}" alt="Image"></a>
                                            <p> {{shop.product}} </p>
                                        </div>
                                    </td>
                                    <td>{{shop.product.price}}</td>
                                    <td>
                    
                                        <strong>{{shop.quantity}}</strong>
                                    </td>
                                    <td>
                                        <strong>{{shop.amount}}</strong>
                                    </td>

                                    <td>
                                        <a href="/order/deletefromcart/{{ shop.id }}"
                                            onclick="return confirm('Delete ! Are you sure?')">
                                            <i class="fa fa-trash"></i>
                                        </a>
                                    </td>


                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>

                                    <th class="empty" colspan="3">Total</th>
                                    <th> {{total}} </th>
                                    {% comment %} <th class="empty" colspan="3"></th> {% endcomment %}
                                </tr>
                            </tfoot>
                        </table>
                        <p> {{shopcart.quantity}} </p>
                        {% if total > 0 %}
                        <a href="/order/orderproduct" class="primary-btn"> Place Order </a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Wishlist End -->

{% endblock  %}


{% block footer  %} {% include 'footer.html' %} {% endblock  %}